name: Docker Build

on:
  pull_request:
  push:
    branches:
      - master
      - feature/*
  release:
    types: [published, created, edited]

jobs:
  build-docker-image:
    env:
      VERSION_NAME=$(date +%s)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t py-protobuf-example:${{VERSION_NAME}}
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_LOGIN_PS }}
      - name: Docker tag image
        run: docker tag py-protobuf-example:${{VERSION_NAME}} saurabhsa/py-protobuf-example
      - name: Docker Push imge to repository
        run: docker push saurabhsa/py-protobuf-example
